function [test1,train1] = GetData()


imds_1 = imageDatastore('Data/Data_test/Carambula', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');

imds_2 = imageDatastore('Data/Data_test/Lychee', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');

imds_3 = imageDatastore('Data/Data_test/Pear', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');

imds_4 = imageDatastore('Data/Data_train/Carambula', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');

imds_5 = imageDatastore('Data/Data_train/Lychee', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');

imds_6 = imageDatastore('Data/Data_train/Pear', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');




test1={imds_1,imds_2,imds_3};

train1={imds_4,imds_5,imds_6};

end

